version: 0.2

phases:
  install:
    commands:
      - echo Installing Mocha...
      - npm install
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - 
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Node.js code
      - 
  post_build:
    commands:
      - echo Build completed on `date`
      - aws s3 cp dist http://s3.amazonaws.com/codepipeline-us-west-2-965847873842/john-positano-resume